//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caphyon.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int Id { get; set; }
        public string Descriere { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public bool Status { get; set; }
    }
}
